import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'
import { Toaster } from 'sonner'
import { Header } from '@/components/Header'
import { WrapperContext } from '@/components/utils/WrapperContext'
import './globals.css'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--display-font',
})
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--body-font',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <div className="h-screen w-screen overflow-hidden">
          <WrapperContext>
            <Header />
            {children}
          </WrapperContext>
        </div>

        <Toaster />
      </body>
    </html>
  )
}
