import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'
import './globals.css'
import ReactQueryProvider from '@/lib/provider/reactQuery'
import { Toaster } from 'sonner'
import { SelectedDayProvider } from '@/contexts/SelectedDayContext'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--display-font',
})
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--body-font',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <SelectedDayProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </SelectedDayProvider>
        <Toaster />
      </body>
    </html>
  )
}
